### ISSUE TITLE
Fehler cliffparnitzky/tiny-mce-font-awesome Erweiterung

### ISSUE THREAD

**Issue by dp-designpilot** [cliffparnitzky/TinyMceFontAwesome#13]
Hallo Cliff

Kannst Du mir sagen, wieso dass das Icon beim TinyMCE von Font Awesome nicht mehr funktioniert (das Icon ist nicht mehr sichtbar)

Seit dem Update von 4.4.46 auf 4.4.47 ist das Icon für die Icons nicht mehr vorhanden beim TinyMCE.

Hab ne frische 4.4.47 Installation aufgesetzt damit ich eventuell den Fehler reproduzieren kann, aber die Installation von cliffparnitzky/tiny-mce-font-awesome lief ohne Probleme durch und auch der Eintrag im Seitenlayout ist angehackt.

Hab gedacht das es einen Konflikt zwischen PHP 7.3 und PHP 7.4 wäre aber das war nicht der Fall.

Danke viel mal für die Hilfe

**Comment by dp-designpilot** [comment]
ah ja auch die frische Installation der 4.4.47 hat nichts gebracht.

**Comment by cliffparnitzky** [comment]
Vielen Dank für den Hinweis. Nach einer Analyse habe ich die Ursache ermitteln können.

Siehe dazu https://github.com/cliffparnitzky/TinyMcePluginLoader/issues/14

**Comment by dp-designpilot** [comment]
was muss ich jetzt genau tun das es wieder funktioniert ???

**Comment by dp-designpilot** [comment]
einfach das gelb markierte dazu schreiben

https://github.com/cliffparnitzky/TinyMcePluginLoader/blob/master/system/modules/TinyMcePluginLoader/classes/TinyMcePluginLoader.php#L45

**Comment by cliffparnitzky** [comment]
Gefixt mit https://github.com/cliffparnitzky/TinyMcePluginLoader/commit/c3f647c1558ff8f6d7a6928b9f1a4bfd890a10e3

Bitte mal via Composer/Contao Manager updaten, so dass https://packagist.org/packages/cliffparnitzky/tiny-mce-plugin-loader auf Version 2.1.10 aktualisiert wird.
