### ISSUE TITLE
Script-Error in Contao 4.11

### ISSUE THREAD

**Issue by rustykowski** [cliffparnitzky/TinyMceFontAwesome#14]
Die Injektion des zusätzlichen content-CSS scheint nicht in C 4.11 nicht sauber zu funktionieren.
Der TinyMCE wird nicht geladen. Im Backend ist nur ein Textarea mit HTML-Quelltext zu sehen.

Die Fehlerkonsole verweist auf:
```
...
file_picker_types: ["image","file"],
  content_css: "system/themes/flexible/tinymce.min.css',
,//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css",
  plugins: "autosave charmap code fullscreen image importcss link lists paste searchreplace stripnbsp tabfocus table visualblocks visualchars',
 noneditable fontawesome",
...
```
Das heißt: Kommas, Anführungszeichen und Zeilenumbruch gehen nicht ganz auf.

**Comment by theDyingMountain** [comment]
Ja, ich kann den Fehler nachvollziehen. Tritt bei mir in einer 4.11 Installation auch auf.

**Comment by cliffparnitzky** [comment]
Plugin not longer supported by vendor. There is no successor plugin for free. This plugin is not compatible with Contao 4.13.
