### ISSUE TITLE
Can't load external css-file

### ISSUE THREAD

**Issue by Tobias-Gl** [cliffparnitzky/TinyMceFontAwesome#2]
Systeminformation:
TinyMcePluginLoader: 2.1.4
Contao: 3.5.0
plugins: tiny-mce-plugin-loader, tiny-mce-font-awesome
installation method: composer

The file <link href = "http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel = "stylesheet"> can not be loaded by the browser when you works over https.
Error message in the browser console: Blocked loading mixed active content "http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"

It is the version 4.3.0 loaded in the backend, the frontend version 4.4.0

faster bugfix: edit ./system/config/fontawesome.php

**Comment by cliffparnitzky** [comment]
Yep, an update save way would be fine ... will be added soon.

**Comment by cliffparnitzky** [comment]
Please read the introduction: https://github.com/cliffparnitzky/TinyMceFontAwesome#change-url-to-font-awesome-css-file
