### ISSUE TITLE
FR: FontAwesome also for navigation modules?

### ISSUE THREAD

**Issue by jscholtysik** [cliffparnitzky/TinyMceFontAwesome#3]
Hi,

is it possible to extend this extension to support FontAwesome also in navigation modules? Or is it better to open a complete new thread for this?

My idea would be that FontAwesome could also be included in navigation modules:
- In a vertical navigation on the left or right side of the menu entry
- In a horizontal navigation on top or bottom of the menu entry and centered related to the width of the menu entry or besides the menu entry on the left or right side
- In a drop down menu also on the left or right side of a menu entry

Thanks in advance.

Joachim

**Comment by cliffparnitzky** [comment]
This module is only a wrapper to put the FontAwesome plugin into the tiny MCE config .. nothing else. Sorry.
