### ISSUE TITLE
tl_layout conflict

### ISSUE THREAD

**Issue by reluem** [cliffparnitzky/TinyMceFontAwesome#4]
The DCA config of this module and [contao-supertheme](https://github.com/comolo/contao-supertheme) are somehow interfering!

`// Add external_js + external_scss
$GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] = str_replace(
    array(',script;', 'stylesheet,external;', 'stylesheet,external,'),
    array(',script,external_js;', 'stylesheet,external,external_scss;', 'stylesheet,external,external_scss,'),
    $GLOBALS['TL_DCA']['tl_layout']['palettes']['default']
);`

interferes with 

`$GLOBALS['TL_DCA']['tl_layout']['palettes']['default'] = str_replace('external', 'external,tinyMceFontAwesome', $GLOBALS['TL_DCA']['tl_layout']['palettes']['default']);`

Thus, only the fontawesome-input is visible and the external_js field is hidden/overwritten.

Any proposals for a local dcaconfig change for this issue?

contao 3.5.6
"comolo/contao-supertheme": ">=2.2.5.0,<2.3-dev",
"cliffparnitzky/tiny-mce-font-awesome": ">=2.0.0.0,<2.1-dev",

**Comment by cliffparnitzky** [comment]
Thanks for the hint.

Your right, extending the palletes via `str_replace` is not best way. But the proposed solution from the linked ticket is to special.

I created the branch `hotfix/tl_layout_conflict`. Please install via composer and test it, to verify correct functionality in your environment.

**Comment by reluem** [comment]
The hotfix and @comolo 's solution did work! thanks a lot

**Comment by cliffparnitzky** [comment]
Great, thanks for the test. The hotfix was mergerd into version [2.0.1](https://github.com/cliffparnitzky/TinyMceFontAwesome/releases/tag/2.0.1).
