### ISSUE TITLE
FontAwesome Plugin produce a error in IE11

### ISSUE THREAD

**Issue by Xeramos** [cliffparnitzky/TinyMceFontAwesome#6]
This Plugin produce a error in the Internet Explorer 11.
If you create a new Element (_Type Text_) and you save the Text, you got the error:
Please fill in the "**Text**" field
and the Textfield is empty

**Comment by cliffparnitzky** [comment]
This seems to be a general problem of the external plugin https://github.com/josh18/TinyMCE-FontAwesome-Plugin. Only adding an icon does not work. This could not be fixed within this extension.
